[technote]
id = "TESTN-123"
series_id = "TESTN"
canonical_url = "https://testn-123.lsst.io"
github_url = "https://github.com/lsst-sqre-testing/testn-123"
github_default_branch = "main"
date_created = 2023-11-28T20:05:13Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Jonathan"
name.family = "Sick"
orcid = "https://orcid.org/0000-0003-3001-676X"
internal_id = "sickj"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
